/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/sofa/scene.gltf 
Author: Mehdi Shahsavan (https://sketchfab.com/ahmagh2e)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-sofa-waiting-room-4mb-7a417ede7dd244dea4b327435f9ee935
Title: Office sofa waiting room - 4MB
*/

import React, { useEffect } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

export function Model(props) {
  const { nodes, materials } = useGLTF("sofa/scene.gltf");
  const { customization } = props;

  let textureProps;
  let woodProps;

  if (customization.fabric) {
    textureProps = useTexture({
      map: customization.fabric,
    });

    textureProps.map.repeat.set(2, 2);
    textureProps.map.wrapS = textureProps.map.wrapT = THREE.RepeatWrapping;
  }

  if (customization.wood) {
    woodProps = useTexture({
      map: customization.wood,
    });

    woodProps.map.repeat.set(2, 2);
    woodProps.map.wrapS = woodProps.map.wrapT = THREE.RepeatWrapping;
  }

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes["01_01_0"].geometry}
          material={materials.material}
          position={[0.16, 72.23, -0.012]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          {customization.fabric && <meshStandardMaterial {...textureProps} />}
        </mesh>
        <mesh
          geometry={nodes["02_2_0"].geometry}
          material={materials.material_1}
          position={[-0.16, 16.836, 0.012]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          {customization.wood && <meshStandardMaterial {...woodProps} />}
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("sofa/scene.gltf");
